### ISSUE TITLE
Chrome complains that this has a virus.

### ISSUE THREAD

**Issue by Methodician** [probot/autoresponder#18]
When attempting to download the as a zip file (the "Download ZIP" option), Chrome says "Failed - Virus detected".

I sure hope there's not a virus. I'm going to use "Open in Desktop" which doesn't seem to mind.

**Comment by bkeepers** [comment]
Weird. I can't duplicate it. You get it when downloading this URL? https://github.com/probot/autoresponder/archive/master.zip

**Comment by Methodician** [comment]
Yes. Here's a screen snip... Basically as soon as I click that, Chrome starts to download and then shows me this in the downloads bar.
![capture](https://user-images.githubusercontent.com/4460470/32074812-66ba5f96-ba4f-11e7-9420-c84bf13867d8.PNG)
So I haven't actually decided to do anything with it, since I'm wary of viral infections.

**Comment by hiimbex** [comment]
I cannot reproduce this either. I suspect this might be specific to your OS's settings regarding file downloads, considering this repo's contents.
