### ISSUE TITLE
critical(autoresponder): Doesn't work at April 2018

### ISSUE THREAD

**Issue by Kristinita** [probot/autoresponder#27]
### 1. Summary

Autoresponder doesn't work for me in 9.4.2018.

In past — February 2018 — Autoresponder [**nice work for me**](https://github.com/Kristinita/SashaProbot/issues/1).

### 2. Configuration

+ [**SashaProbot GitHub repository**](https://github.com/Kristinita/SashaProbot/),
+ [**.github/ISSUE_REPLY_TEMPLATE.md file**](https://github.com/Kristinita/SashaProbot/blob/master/.github/ISSUE_REPLY_TEMPLATE.md).

Autoresponder configure for this repository:

![Configure 1](https://i.imgur.com/GpzsqrJ.png)
![Configure 2](https://i.imgur.com/pReteU3.png)

### 3. Steps to reproduce

I [**create an issue**](https://github.com/Kristinita/SashaProbot/issues/11) in SashaProbot repository.

### 4. Expected behavior

[**autoresponder comment**](https://github.com/Kristinita/SashaProbot/issues/1#issuecomment-364753346) from `ISSUE_REPLY_TEMPLATE.md`.

### 5. Actual behavior

Nothing occurs.

Thanks.

**Comment by bkeepers** [comment]
It's all fixed up. Thanks for reporting it, and sorry for the delay in fixing it.
